apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-location-config
data:
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: ip-location-secrets
type: Opaque
stringData:
  # 如果您使用付费的 IP 地理位置 API，可以在此处添加密钥
  API_KEY: ""
