name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  ACR_RESOURCE_GROUP: wprg001
  ACR_NAME: iplocationacr
  IMAGE_NAME: ip-location
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AKS_CLUSTER_NAME: wpaks001
  AKS_RESOURCE_GROUP: wprg001
  NAMESPACE: ip-location-ns
  DOMAIN_NAME: ip-location.example.com  # 替换成您的实际域名

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint || echo "No linting configured"

    - name: Run tests
      run: npm test || echo "No tests configured"

  build-and-push:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      BUILD_ID: ${{ steps.build-id.outputs.id }}
      ACR_LOGIN_SERVER: ${{ steps.set-acr.outputs.login_server }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set ACR login server
      id: set-acr
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} --resource-group ${{ env.ACR_RESOURCE_GROUP }} --query loginServer -o tsv)
        echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
        echo "login_server=$ACR_LOGIN_SERVER" >> $GITHUB_OUTPUT
      
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Generate build ID
      id: build-id
      run: |
        BUILD_ID=$(date +%Y%m%d)-$(echo ${{ github.sha }} | cut -c1-7)
        echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
        echo "id=$BUILD_ID" >> $GITHUB_OUTPUT
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}

  deploy-to-aks:
    needs: build-and-push
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Create namespace if not exists
      run: kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -    # 替换 Kubernetes 配置文件中的变量
    - name: Prepare Kubernetes manifests
      run: |
        cd kubernetes
        CONTAINER_REGISTRY="${{ needs.build-and-push.outputs.ACR_LOGIN_SERVER }}"
        IMAGE_NAME="${{ env.IMAGE_NAME }}"
        IMAGE_TAG="${{ needs.build-and-push.outputs.BUILD_ID }}"
        
        # Debug output to verify variables
        echo "Debug - Variables:"
        echo "CONTAINER_REGISTRY: $CONTAINER_REGISTRY"
        echo "IMAGE_NAME: $IMAGE_NAME"
        echo "IMAGE_TAG: $IMAGE_TAG"
        echo "FULL IMAGE: $CONTAINER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
        
        # Check if ACR_LOGIN_SERVER is actually set
        if [ -z "$CONTAINER_REGISTRY" ]; then
          echo "ERROR: CONTAINER_REGISTRY is empty - using fallback value"
          CONTAINER_REGISTRY="${{ env.ACR_NAME }}.azurecr.io"
        fi
        
        # Make replacements and verify result
        sed -i "s|\${CONTAINER_REGISTRY}|$CONTAINER_REGISTRY|g" deployment.yaml
        sed -i "s|\${IMAGE_NAME}|$IMAGE_NAME|g" deployment.yaml
        sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" deployment.yaml
        sed -i "s|DOMAIN_NAME_PLACEHOLDER|${{ env.DOMAIN_NAME }}|g" deployment.yaml
        
        # Verify substitution worked
        echo "After substitution - Image in deployment.yaml:"
        grep -A 1 "image:" deployment.yaml
        

        
    # Verify image exists in ACR
    - name: Verify image in ACR
      run: |
        IMAGE="${{ needs.build-and-push.outputs.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.BUILD_ID }}"
        echo "Checking if image exists: $IMAGE"
        az acr repository show \
          --name ${{ env.ACR_NAME }} \
          --image ${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.BUILD_ID }} || \
        echo "WARNING: Image not found in ACR. This may cause deployment failures."

    # Deploy to AKS
    - name: Deploy to AKS
      run: |
        kubectl apply -f kubernetes/deployment.yaml -n ${{ env.NAMESPACE }}
        kubectl rollout restart deployment/ip-location -n ${{ env.NAMESPACE }}

    # Verify deployment
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/ip-location -n ${{ env.NAMESPACE }}
        kubectl get services,deployments,pods -n ${{ env.NAMESPACE }}

    # 检查 NGINX Ingress Controller 是否可用
    - name: Check NGINX Ingress Controller Status
      run: |
        # 检查 admission webhook endpoints 是否存在
        ENDPOINTS=$(kubectl get endpoints -n ingress-basic nginx-ingress-ingress-nginx-controller-admission --no-headers --ignore-not-found | awk '{print $2}')
        if [ -z "$ENDPOINTS" ] || [ "$ENDPOINTS" = "<none>" ]; then
          echo "WARNING: NGINX Ingress Controller admission webhook endpoints 不可用。"
          echo "请确保已在 AKS 集群中正确安装并启动 NGINX Ingress Controller。"
          echo "参考：https://kubernetes.github.io/ingress-nginx/deploy/"
          echo "Ingress 资源已通过 deployment.yaml 申请，但可能无法正常工作。"
        else
          echo "NGINX Ingress Controller admission webhook endpoints 可用，Ingress 资源应该能正常工作。"
        fi
